{{- if and .Values.management.enabled (not .Values.management.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reaper.management.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reaper.labels" . | nindent 4 }}
    app.kubernetes.io/component: management
type: Opaque
stringData:
  REAPER_JWT_SECRET: {{ .Values.management.secrets.jwtSecret | default (randAlphaNum 32) | quote }}
  REAPER_DATABASE_URL: {{ include "reaper.postgresql.url" . | quote }}
{{- end }}
