{{- if and .Values.platform.enabled .Values.platform.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "reaper.platform.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reaper.labels" . | nindent 4 }}
    app.kubernetes.io/component: platform
spec:
  accessModes:
    {{- toYaml .Values.platform.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.platform.persistence.size }}
  {{- if or .Values.platform.persistence.storageClass .Values.global.storageClass }}
  storageClassName: {{ .Values.platform.persistence.storageClass | default .Values.global.storageClass }}
  {{- end }}
{{- end }}
