[workspace]
resolver = "2"
members = [
    "crates/reaper-core",
    "crates/policy-engine", 
    "crates/message-queue",
    "crates/metrics",
    "services/reaper-agent",
    "services/reaper-platform",
    "tools/reaper-cli",
]

[workspace.dependencies]
# Core async runtime
tokio = { version = "1.0", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
thiserror = "2.0"
anyhow = "1.0"

# Utilities
uuid = { version = "1.0", features = ["v4", "serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4.0", features = ["derive"] }

# Performance-oriented data structures
dashmap = "6.1.0"
parking_lot = "0.12"

# Testing frameworks
tokio-test = "0.4"
criterion = { version = "0.7", features = ["html_reports"] }
proptest = "1.0"

# BDD Testing
cucumber = "0.21.1"
async-trait = "0.1"

# Web framework for API services
axum = { version = "0.8.4", features = ["json", "tokio"] }
tower = "0.5.2"
hyper = "1.0"

[workspace.metadata.release]
shared-version = true
tag-message = "Reaper {{version}}"
pre-release-commit-message = "chore: Release Reaper {{version}}"
post-release-commit-message = "chore: Bump to next dev version"
