[package]
name = "reaper-agent"
version = "0.1.0"
edition = "2021"
description = "Reaper Agent - High-performance policy enforcement"

[dependencies]
reaper-core = { path = "../../crates/reaper-core" }
policy-engine = { path = "../../crates/policy-engine" }
message-queue = { path = "../../crates/message-queue" }
metrics = { path = "../../crates/metrics" }
axum = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tower = { workspace = true }
uuid = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
criterion = { workspace = true }
cucumber = { workspace = true }
async-trait = { workspace = true }
hyper = { workspace = true }

[[bench]]
name = "agent_bench"
harness = false

[[test]]
name = "agent_bdd_tests"
harness = false
